experiment_name: "nuscenes_resnet50_baseline"

training:
  dataset: "trainval"
  max_iterations: 100000
  log_interval: 1000
  batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 0.0001
  weight_decay: 0.01
  use_scheduler: True
  shuffle: True
  validate: False
  validate_interval: 5000 
  num_workers: 4
  keep_latest: 3
  ignore_load_errors: False 
  load_step: False 
  load_optimizer: False

data:
  base_resolution:
    width: 400
    height: 224
  resolution_scale: 2 
  random_flip: True 
  random_crop_and_resize: True 
  num_cameras: 6
  num_sweeps: 3

model:
  encoder_type: "resnet50"
  use_radar: False
  use_radar_filter: False
  use_lidar: False
  use_metaradar: False
  compress_rgb: True
  shuffle_cameras: True
 
paths:
  config_path: "config.yaml"
  data_directory: "../nuscenes"
  log_directory: "logs/"
  checkpoint_directory: "checkpoints/"
  load_directory: ""

